services:
  nest-postgres:
    image: postgres:14-alpine
    container_name: nest-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    volumes:
      - nest-postgres:/var/lib/postgresql/data

volumes:
  nest-postgres:
    name: nest-postgres-db
